Repository aicoe-aiops/time-series, pull requests merged in 2021-04, with the labels that each got.

#20 Add forecasting notebook
  notebooks/ts-4-forecasting.ipynb
Labels: approved, size/XXL

#22 Add Linear and Exponential models
  data/raw/ts.pkl
  notebooks/ts-3-concepts.ipynb
Labels: size/XXL

#30 Update Owners
  OWNERS
Labels: lgtm, size/XS
